"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UIM_TEMPLATE_SIMULATE = exports.UIM_TEMPLATE_CLONE = exports.UIM_TEMPLATE_UPDATE = exports.UIM_TEMPLATE_CREATE = exports.UIM_TEMPLATE_DETAIL_PANEL_PREVIEW_TAB = exports.UIM_TEMPLATE_DETAIL_PANEL_ALIASES_TAB = exports.UIM_TEMPLATE_DETAIL_PANEL_MAPPINGS_TAB = exports.UIM_TEMPLATE_DETAIL_PANEL_SETTINGS_TAB = exports.UIM_TEMPLATE_DETAIL_PANEL_SUMMARY_TAB = exports.UIM_TEMPLATE_SHOW_DETAILS_CLICK = exports.UIM_TEMPLATE_DELETE_MANY = exports.UIM_TEMPLATE_DELETE = exports.UIM_TEMPLATE_LIST_LOAD = exports.UIM_DETAIL_PANEL_SUMMARY_TAB = exports.UIM_DETAIL_PANEL_STATS_TAB = exports.UIM_DETAIL_PANEL_SETTINGS_TAB = exports.UIM_DETAIL_PANEL_MAPPING_TAB = exports.UIM_DETAIL_PANEL_EDIT_SETTINGS_TAB = exports.UIM_SHOW_DETAILS_CLICK = exports.UIM_INDEX_UNFREEZE_MANY = exports.UIM_INDEX_UNFREEZE = exports.UIM_INDEX_SETTINGS_EDIT = exports.UIM_INDEX_REFRESH_MANY = exports.UIM_INDEX_REFRESH = exports.UIM_INDEX_OPEN_MANY = exports.UIM_INDEX_OPEN = exports.UIM_INDEX_FREEZE_MANY = exports.UIM_INDEX_FREEZE = exports.UIM_INDEX_FORCE_MERGE_MANY = exports.UIM_INDEX_FORCE_MERGE = exports.UIM_INDEX_FLUSH_MANY = exports.UIM_INDEX_FLUSH = exports.UIM_INDEX_DELETE_MANY = exports.UIM_INDEX_DELETE = exports.UIM_INDEX_CLOSE_MANY = exports.UIM_INDEX_CLOSE = exports.UIM_INDEX_CLEAR_CACHE_MANY = exports.UIM_INDEX_CLEAR_CACHE = exports.UIM_UPDATE_SETTINGS = exports.UIM_APP_LOAD = exports.UIM_APP_NAME = void 0;
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

const UIM_APP_NAME = 'index_management';
exports.UIM_APP_NAME = UIM_APP_NAME;
const UIM_APP_LOAD = 'app_load';
exports.UIM_APP_LOAD = UIM_APP_LOAD;
const UIM_UPDATE_SETTINGS = 'update_settings';
exports.UIM_UPDATE_SETTINGS = UIM_UPDATE_SETTINGS;
const UIM_INDEX_CLEAR_CACHE = 'index_clear_cache';
exports.UIM_INDEX_CLEAR_CACHE = UIM_INDEX_CLEAR_CACHE;
const UIM_INDEX_CLEAR_CACHE_MANY = 'index_clear_cache_many';
exports.UIM_INDEX_CLEAR_CACHE_MANY = UIM_INDEX_CLEAR_CACHE_MANY;
const UIM_INDEX_CLOSE = 'index_close';
exports.UIM_INDEX_CLOSE = UIM_INDEX_CLOSE;
const UIM_INDEX_CLOSE_MANY = 'index_close_many';
exports.UIM_INDEX_CLOSE_MANY = UIM_INDEX_CLOSE_MANY;
const UIM_INDEX_DELETE = 'index_delete';
exports.UIM_INDEX_DELETE = UIM_INDEX_DELETE;
const UIM_INDEX_DELETE_MANY = 'index_delete_many';
exports.UIM_INDEX_DELETE_MANY = UIM_INDEX_DELETE_MANY;
const UIM_INDEX_FLUSH = 'index_flush';
exports.UIM_INDEX_FLUSH = UIM_INDEX_FLUSH;
const UIM_INDEX_FLUSH_MANY = 'index_flush_many';
exports.UIM_INDEX_FLUSH_MANY = UIM_INDEX_FLUSH_MANY;
const UIM_INDEX_FORCE_MERGE = 'index_force_merge';
exports.UIM_INDEX_FORCE_MERGE = UIM_INDEX_FORCE_MERGE;
const UIM_INDEX_FORCE_MERGE_MANY = 'index_force_merge_many';
exports.UIM_INDEX_FORCE_MERGE_MANY = UIM_INDEX_FORCE_MERGE_MANY;
const UIM_INDEX_FREEZE = 'index_freeze';
exports.UIM_INDEX_FREEZE = UIM_INDEX_FREEZE;
const UIM_INDEX_FREEZE_MANY = 'index_freeze_many';
exports.UIM_INDEX_FREEZE_MANY = UIM_INDEX_FREEZE_MANY;
const UIM_INDEX_OPEN = 'index_open';
exports.UIM_INDEX_OPEN = UIM_INDEX_OPEN;
const UIM_INDEX_OPEN_MANY = 'index_open_many';
exports.UIM_INDEX_OPEN_MANY = UIM_INDEX_OPEN_MANY;
const UIM_INDEX_REFRESH = 'index_refresh';
exports.UIM_INDEX_REFRESH = UIM_INDEX_REFRESH;
const UIM_INDEX_REFRESH_MANY = 'index_refresh_many';
exports.UIM_INDEX_REFRESH_MANY = UIM_INDEX_REFRESH_MANY;
const UIM_INDEX_SETTINGS_EDIT = 'index_settings_edit';
exports.UIM_INDEX_SETTINGS_EDIT = UIM_INDEX_SETTINGS_EDIT;
const UIM_INDEX_UNFREEZE = 'index_unfreeze';
exports.UIM_INDEX_UNFREEZE = UIM_INDEX_UNFREEZE;
const UIM_INDEX_UNFREEZE_MANY = 'index_unfreeze_many';
exports.UIM_INDEX_UNFREEZE_MANY = UIM_INDEX_UNFREEZE_MANY;
const UIM_SHOW_DETAILS_CLICK = 'show_details_click';
exports.UIM_SHOW_DETAILS_CLICK = UIM_SHOW_DETAILS_CLICK;
const UIM_DETAIL_PANEL_EDIT_SETTINGS_TAB = 'detail_panel_edit_settings_tab';
exports.UIM_DETAIL_PANEL_EDIT_SETTINGS_TAB = UIM_DETAIL_PANEL_EDIT_SETTINGS_TAB;
const UIM_DETAIL_PANEL_MAPPING_TAB = 'detail_panel_mapping_tab';
exports.UIM_DETAIL_PANEL_MAPPING_TAB = UIM_DETAIL_PANEL_MAPPING_TAB;
const UIM_DETAIL_PANEL_SETTINGS_TAB = 'detail_panel_settings_tab';
exports.UIM_DETAIL_PANEL_SETTINGS_TAB = UIM_DETAIL_PANEL_SETTINGS_TAB;
const UIM_DETAIL_PANEL_STATS_TAB = 'detail_panel_stats_tab';
exports.UIM_DETAIL_PANEL_STATS_TAB = UIM_DETAIL_PANEL_STATS_TAB;
const UIM_DETAIL_PANEL_SUMMARY_TAB = 'detail_panel_summary_tab';
exports.UIM_DETAIL_PANEL_SUMMARY_TAB = UIM_DETAIL_PANEL_SUMMARY_TAB;
const UIM_TEMPLATE_LIST_LOAD = 'template_list_load';
exports.UIM_TEMPLATE_LIST_LOAD = UIM_TEMPLATE_LIST_LOAD;
const UIM_TEMPLATE_DELETE = 'template_delete';
exports.UIM_TEMPLATE_DELETE = UIM_TEMPLATE_DELETE;
const UIM_TEMPLATE_DELETE_MANY = 'template_delete_many';
exports.UIM_TEMPLATE_DELETE_MANY = UIM_TEMPLATE_DELETE_MANY;
const UIM_TEMPLATE_SHOW_DETAILS_CLICK = 'template_show_details_click';
exports.UIM_TEMPLATE_SHOW_DETAILS_CLICK = UIM_TEMPLATE_SHOW_DETAILS_CLICK;
const UIM_TEMPLATE_DETAIL_PANEL_SUMMARY_TAB = 'template_details_summary_tab';
exports.UIM_TEMPLATE_DETAIL_PANEL_SUMMARY_TAB = UIM_TEMPLATE_DETAIL_PANEL_SUMMARY_TAB;
const UIM_TEMPLATE_DETAIL_PANEL_SETTINGS_TAB = 'template_details_settings_tab';
exports.UIM_TEMPLATE_DETAIL_PANEL_SETTINGS_TAB = UIM_TEMPLATE_DETAIL_PANEL_SETTINGS_TAB;
const UIM_TEMPLATE_DETAIL_PANEL_MAPPINGS_TAB = 'template_details_mappings_tab';
exports.UIM_TEMPLATE_DETAIL_PANEL_MAPPINGS_TAB = UIM_TEMPLATE_DETAIL_PANEL_MAPPINGS_TAB;
const UIM_TEMPLATE_DETAIL_PANEL_ALIASES_TAB = 'template_details_aliases_tab';
exports.UIM_TEMPLATE_DETAIL_PANEL_ALIASES_TAB = UIM_TEMPLATE_DETAIL_PANEL_ALIASES_TAB;
const UIM_TEMPLATE_DETAIL_PANEL_PREVIEW_TAB = 'template_details_preview_tab';
exports.UIM_TEMPLATE_DETAIL_PANEL_PREVIEW_TAB = UIM_TEMPLATE_DETAIL_PANEL_PREVIEW_TAB;
const UIM_TEMPLATE_CREATE = 'template_create';
exports.UIM_TEMPLATE_CREATE = UIM_TEMPLATE_CREATE;
const UIM_TEMPLATE_UPDATE = 'template_update';
exports.UIM_TEMPLATE_UPDATE = UIM_TEMPLATE_UPDATE;
const UIM_TEMPLATE_CLONE = 'template_clone';
exports.UIM_TEMPLATE_CLONE = UIM_TEMPLATE_CLONE;
const UIM_TEMPLATE_SIMULATE = 'template_simulate';
exports.UIM_TEMPLATE_SIMULATE = UIM_TEMPLATE_SIMULATE;